### ISSUE TITLE
GLM does not compile

### ISSUE THREAD

**Issue by peti** [sordina/GLM#1]
Citing from http://hydra.cryp.to/build/1311739/log/raw:

```
src/JSONMain.hs:3:18:
    Could not find module ‘GLM.JSON’
    Use -v to see a list of the files searched for.
```

These files appear to be missing from the release tarball.

**Comment by sordina** [comment]
Hi @peti ,

That's interesting, I'll fix this up ASAP.

**Comment by sordina** [comment]
Should be resolved now.

36923fb..8695cc5

Closing and will re-open if the issue persists.

Sorry about the delay. I didn't see this issue until just now.
